;;; cypher-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cypher-mode.el

(autoload 'cypher-mode "cypher-mode" "\
Major mode for editing web templates.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.cypher\\'" . cypher-mode))
(add-to-list 'auto-mode-alist '("\\.cyp\\'" . cypher-mode))
(register-definition-prefixes "cypher-mode" '("cypher-"))

;;; End of scraped data

(provide 'cypher-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cypher-mode-autoloads.el ends here
