;;; native-complete-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from native-complete.el

(autoload 'native-complete-setup-bash "native-complete" "\
Setup support for native-complete enabled bash shells.
This involves not sending the `--noediting' argument as well as
setting `TERM' to a value other then dumb." t)
(autoload 'native-complete-at-point "native-complete" "\
Get the candidates from the underlying shell.
This should behave the same as sending TAB in an terminal
emulator.")
(autoload 'native-complete-check-config "native-complete" nil t)
(register-definition-prefixes "native-complete" '("native-complete-"))

;;; End of scraped data

(provide 'native-complete-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; native-complete-autoloads.el ends here
